# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Note < Formula
  desc "A modern TUI for note application"
  homepage "https://github.com/armand-sauzay/note"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/armand-sauzay/note/releases/download/v0.2.0/note_0.2.0_darwin_amd64.tar.gz"
      sha256 "a010cb805ef0b7f19efbfebf73ec728391775d86727eede7ee15058fea630220"

      def install
        bin.install "note"
      end
    end
    on_arm do
      url "https://github.com/armand-sauzay/note/releases/download/v0.2.0/note_0.2.0_darwin_arm64.tar.gz"
      sha256 "14c78b5a78ceba32000de0e0ac9a65615796c1cfc1076045ed89e812cafc9bbf"

      def install
        bin.install "note"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.2.0/note_0.2.0_linux_amd64.tar.gz"
        sha256 "e1f135171f456b3ad0f7c6d48de2288a6da3578a95247d1d75a6b27f4683a618"

        def install
          bin.install "note"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.2.0/note_0.2.0_linux_arm64.tar.gz"
        sha256 "7953e261e69cbff1f327d61783f30d1c6996af25fcf6af38afe8d5c2d818bb28"

        def install
          bin.install "note"
        end
      end
    end
  end

  test do
    system "#{bin}/note --version"
  end
end
