# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Note < Formula
  desc "A modern TUI for note application"
  homepage "https://github.com/armand-sauzay/note"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/armand-sauzay/note/releases/download/v0.1.1/note_0.1.1_darwin_amd64.tar.gz"
      sha256 "5f34f984fea4f06a0edb245b68869c126ddd38ec4c81ab3067ebf395d18643bb"

      def install
        bin.install "note"
      end
    end
    on_arm do
      url "https://github.com/armand-sauzay/note/releases/download/v0.1.1/note_0.1.1_darwin_arm64.tar.gz"
      sha256 "beb1e224d25f79e86dafaa5d03b8579092a77b008f88b2f7d1dc9a15b1d3cc7d"

      def install
        bin.install "note"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.1.1/note_0.1.1_linux_amd64.tar.gz"
        sha256 "7d7735435bc53990480c986c34a820dbd1e84a1c6dcc26385811cc62782f1756"

        def install
          bin.install "note"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.1.1/note_0.1.1_linux_arm64.tar.gz"
        sha256 "8ced2522edeae217aeb4c109c24b4a551c2fd6624948a062f9c13b8e7f05b7a9"

        def install
          bin.install "note"
        end
      end
    end
  end

  test do
    system "#{bin}/note --version"
  end
end
