# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Note < Formula
  desc "A modern TUI for note application"
  homepage "https://github.com/armand-sauzay/note"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/armand-sauzay/note/releases/download/v0.3.0/note_0.3.0_darwin_amd64.tar.gz"
      sha256 "6a202e3252e6196149a4075fbe40fbb85e1021f66013ec09fd0cb06bd31a6ed1"

      def install
        bin.install "note"
      end
    end
    on_arm do
      url "https://github.com/armand-sauzay/note/releases/download/v0.3.0/note_0.3.0_darwin_arm64.tar.gz"
      sha256 "9b9e4d04837734004a8b7c5a5f00aa4c9d819ec6488d13467fe2c1b3145b9f5a"

      def install
        bin.install "note"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.3.0/note_0.3.0_linux_amd64.tar.gz"
        sha256 "9ab815389228a8f887f6532cba977d618545907baa19cc523319d9ff3460ac03"

        def install
          bin.install "note"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/armand-sauzay/note/releases/download/v0.3.0/note_0.3.0_linux_arm64.tar.gz"
        sha256 "5b4f9275f3794e4acf65b96971aabad8ea1ab1723b0541efc5302ac1b32de9b1"

        def install
          bin.install "note"
        end
      end
    end
  end

  test do
    system "#{bin}/note --version"
  end
end
